### ISSUE TITLE
Convert numbers directly

### ISSUE THREAD

**Issue by dy** [mikolalysenko/to-px#1]
Oftentimes there is a case converting size to pixels:

```js
let parseUnit = require('parse-unit')
let px = require('to-px')

let size = '12rem'
let unit = parseUnit(size) // [12, 'rem']
let pxSize = unit[0] * px(unit[1]) // 12 * 16
```

Just wonder if extending the API to cover that case would be meaningful:

```js
let px = require('to-px')

px('12rem')  // 12 * 16
```

@mikolalysenko it feels natural to implement that here, or is it better to delegate to a separate package eg. `require('px-size')`?

**Comment by dy** [comment]
@mikolalysenko ping. I can make a PR

**Comment by dy** [comment]
@mikolalysenko ping

**Comment by mikolalysenko** [comment]
Makes sense, if you want to add it go right ahead
